repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: requirements-txt-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            'flake8-bandit==4.1.1',
            'flake8-bugbear==23.1.20',
            'flake8-docstrings==1.7.0',
            'flake8-rst-docstrings==0.3.0',
            'pep8-naming==0.13.3',
          ]
