image: python:3.10.12

definitions:
  steps:
    - step: &evaluate
        name: Evaluate
        deployment: Test
        caches:
          - pip
        script:
          - ssh-keyscan -H $DEV_IP >> ~/.ssh/known_hosts
          - ssh -NL 7000:localhost:7000 -f ubuntu@$DEV_IP
          - pip install -r requirements-eval.txt
          - cd src
          - python validation/pipeline.py
        artifacts:
          - src/validation/logs/**

    - step: &push-image-to-azure
        name: release-new-chatbot-version
        script:
          - pip install poetry
          - ./scripts/release_version.sh
        services:
          - docker


pipelines:
  branches:
    master:
      - step:
          <<: *evaluate
          name: evaluate-new-chatbot-version
          deployment: Test
      - step:
          <<: *push-image-to-azure
          name: release-new-chatbot-version
          deployment: Production
    staging:
      - step:
          <<: *evaluate
          name: evaluate-new-chatbot-dev-version
          deployment: Test
      - step:
          <<: *push-image-to-azure
          name: release-new-chatbot-dev-version
          deployment: Staging

  custom:
    evaluation-pipeline:
      - variables:
          - name: PIPELINE_NAME
            default: chatbot_eval
          - name: CHATBOT_MODEL
            default: gpt-3.5-turbo-azure
            allowed-values:
              - gpt-3.5-turbo-azure
              - gpt-3.5-turbo
              - gpt-4
          - name: DISABLE_MEMORY
            default: false
            allowed-values:
              - false
              - true
          - name: DISABLE_FAQ
            default: false
            allowed-values:
              - false
              - true
          - name: USE_NSX_SENSE
            default: false
            allowed-values:
              - false
              - true
          - name: MAX_DATASET_QUESTIONS
            default: -1
          - name: MAX_VARIANT_QUESTIONS
            default: 1
      - step: *evaluate

    push-custom-image-to-azure:
      - step:
          name: push-custom-image-to-azure
          deployment: Test
          script:
            - ./scripts/push_custom_docker_image.sh $BITBUCKET_BRANCH
          services:
            - docker
