image: python:3.10.12

definitions:
  steps:
    - step: &evaluate
        name: Evaluate
        caches:
          - pip
        script:
          - |
            if [ "$SERVER" = "dev" ]; then
              SERVER_IP=$DEV_IP
            elif [ "$SERVER" = "prod" ]; then
              SERVER_IP=$PROD_IP
            fi
          - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          - ssh -NL 7000:localhost:7000 -f ubuntu@$SERVER_IP
          - pip install -r requirements-eval.txt
          - cd src
          - export ENVIRONMENT=eval
          - python validation/pipeline.py
        artifacts:
          - src/validation/logs/**

    - step: &push-image-to-azure
        name: release-new-chatbot-version
        script:
          - pip install poetry
          - ./scripts/release_version.sh
        services:
          - docker

pipelines:
  branches:
    master:
      - stage:
          name: deploy-to-prod
          deployment: Production
          steps:
            - step:
                <<: *evaluate
                name: evaluate-new-chatbot-version
            - step:
                <<: *push-image-to-azure
                name: release-new-chatbot-version
    staging:
      - stage:
          name: deploy-to-dev
          deployment: Staging
          steps:
            - step:
                <<: *evaluate
                name: evaluate-new-chatbot-dev-version
            - step:
                <<: *push-image-to-azure
                name: release-new-chatbot-dev-version

  custom:
    evaluation-pipeline:
      - variables:
          - name: SERVER
            default: dev
            allowed-values:
              - dev
              - prod
          - name: PIPELINE_NAME
            default: chatbot_eval
          - name: CHATBOT_MODEL
            default: gpt-3.5-turbo-azure
            allowed-values:
              - gpt-3.5-turbo-azure
              - gpt-3.5-turbo-0613-azure
              - gpt-3.5-turbo-16k-azure
              - gpt-3.5-turbo
              - gpt-3.5-turbo-16k
              - gpt-4
          - name: DISABLE_MEMORY
            default: false
            allowed-values:
              - false
              - true
          - name: DISABLE_FAQ
            default: false
            allowed-values:
              - false
              - true
          - name: USE_NSX_SENSE
            default: false
            allowed-values:
              - false
              - true
          - name: BM25_ONLY
            default: false
            allowed-values:
              - false
              - true
          - name: MAX_DATASET_QUESTIONS
            default: -1
          - name: MAX_VARIANT_QUESTIONS
            default: 1
          - name: EVALUATION_INDEXES
            default: "[]"
          - name: INDEX_MAPPING
            default: "{}"

      - step:
          <<: *evaluate
          name: evaluate-new-chatbot-dev-version

    push-custom-image-to-azure:
      - step:
          name: push-custom-image-to-azure
          deployment: Test
          script:
            - ./scripts/push_custom_docker_image.sh $BITBUCKET_BRANCH
          services:
            - docker
