"""
Parse log files to csv files.

This script parses the log files generated by the validation pipeline and
converts them to csv files. The csv files are stored in the same directory
as the log files.

The aim of this script is to make it easier to analyze the logs.

Example:
    $ python log_to_table.py


"""

import json
from pathlib import Path

import pandas as pd

logs = Path("logs/")

for directory in logs.iterdir():
    print(directory.name)
    for log_path in directory.iterdir():
        if log_path.suffix == ".json":
            print(log_path.name)
            with log_path.open("r", encoding="utf-8") as f:
                log = json.load(f)
            dataframe = pd.DataFrame(log["log"])
            dataframe.to_csv(
                directory / f"{log_path.stem}.csv", index=False, encoding="utf-8"
            )
